# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ultra96v2_oob/ultra96v2_oob.xdc

# XDC: /home/sho/work/vivado/avnet/hdl/Projects/ultra96v2_oob/ultra96v2_oob.xdc

# Block Designs: bd/ultra96v2_oob/ultra96v2_oob.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob || ORIG_REF_NAME==ultra96v2_oob} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_zynq_ultra_ps_e_0_0/ultra96v2_oob_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ultra96v2_oob_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_axi_uart16550_0_0/ultra96v2_oob_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_axi_uart16550_0_0 || ORIG_REF_NAME==ultra96v2_oob_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xbar_0/ultra96v2_oob_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xbar_0 || ORIG_REF_NAME==ultra96v2_oob_xbar_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_ps8_0_axi_periph_0/ultra96v2_oob_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_ps8_0_axi_periph_0 || ORIG_REF_NAME==ultra96v2_oob_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_rst_ps8_0_100M_0/ultra96v2_oob_rst_ps8_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_rst_ps8_0_100M_0 || ORIG_REF_NAME==ultra96v2_oob_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_axi_uart16550_1_0/ultra96v2_oob_axi_uart16550_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_axi_uart16550_1_0 || ORIG_REF_NAME==ultra96v2_oob_axi_uart16550_1_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_axi_gpio_0_0/ultra96v2_oob_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_axi_gpio_0_0 || ORIG_REF_NAME==ultra96v2_oob_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_axi_gpio_1_0/ultra96v2_oob_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_axi_gpio_1_0 || ORIG_REF_NAME==ultra96v2_oob_axi_gpio_1_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_axi_gpio_2_0/ultra96v2_oob_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_axi_gpio_2_0 || ORIG_REF_NAME==ultra96v2_oob_axi_gpio_2_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_PWM_w_Int_0_0/ultra96v2_oob_PWM_w_Int_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_PWM_w_Int_0_0 || ORIG_REF_NAME==ultra96v2_oob_PWM_w_Int_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_PWM_w_Int_1_0/ultra96v2_oob_PWM_w_Int_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_PWM_w_Int_1_0 || ORIG_REF_NAME==ultra96v2_oob_PWM_w_Int_1_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_system_management_wiz_0_0/ultra96v2_oob_system_management_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_system_management_wiz_0_0 || ORIG_REF_NAME==ultra96v2_oob_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlconcat_0_0/ultra96v2_oob_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlconcat_0_0 || ORIG_REF_NAME==ultra96v2_oob_xlconcat_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_0_0/ultra96v2_oob_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_0_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_1_0/ultra96v2_oob_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_1_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_1_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_2_0/ultra96v2_oob_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_2_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_2_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_3_0/ultra96v2_oob_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_3_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_3_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_4_0/ultra96v2_oob_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_4_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_4_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_5_0/ultra96v2_oob_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_5_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_5_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_6_0/ultra96v2_oob_xlslice_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_6_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_6_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_7_0/ultra96v2_oob_xlslice_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_7_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_7_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_8_0/ultra96v2_oob_xlslice_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_8_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_8_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_9_0/ultra96v2_oob_xlslice_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_9_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_9_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_ds_0/ultra96v2_oob_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_ds_0 || ORIG_REF_NAME==ultra96v2_oob_auto_ds_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_pc_0/ultra96v2_oob_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_pc_0 || ORIG_REF_NAME==ultra96v2_oob_auto_pc_0} -quiet] -quiet

# XDC: bd/ultra96v2_oob/ultra96v2_oob_ooc.xdc
